sudo: required
git:
  depth: 1
services:
- docker
notifications:
  email:
    on_success: never
    on_failure: always
script:
- docker build --build-arg "VERSION=${TRAVIS_COMMIT:0:6}" -t "nrocco/bookmarks:${TRAVIS_COMMIT:0:6}" .
deploy:
  provider: script
  script:
  - 'echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin'
  - 'docker image tag nrocco/bookmarks:${TRAVIS_COMMIT:0:6} nrocco/bookmarks:latest'
  - 'docker image push nrocco/bookmarks:${TRAVIS_COMMIT:0:6}'
  - 'docker image push nrocco/bookmarks:latest'
  - 'wget -O /dev/null --header="Token: ${DEPLOY_TOKEN}" "https://webhooks.casadirocco.nl/hooks/deploy?service=bookmarks&tag=${TRAVIS_COMMIT:0:6}"'
  on:
    branch: master
env:
  global:
    - secure: "l8l/7EeJlH702VoQ4EWeBgPZr0PUt0wxoxhCkRVhXCFF/YRDv23F+pzPiwDNbXr42KP4zLOzl/5UgbJxSlxaTveX8LpyHoi0mS5EVXF4iaHhqCM7kO44I+2jKczhqvjGnk/NcRJuhHtCsJ3+9WApTS4aUDHRb79ScbFvgtOPql1398rooAmdizpZ+AFQqweRzacZrKbTM5TNy0KDtxKV1bMzLIV8LtbE1PS5FVAyFBUGHY1m3wuB99ICTIUTleS07SW87XNsR95mHikH+Md5AhQOBHavAPv/1AHnrNuDuAlj/cKkoihVAB0VQ9ksC2Xj+E7fJpIyQjVET4MDQImZa8tzcO8aG1gupKVLXyOaHAU3cAyNFLVlJUv+bsWVl1MAx40YbIAlrL5PnNvzGEBRGsoPtUOQNgSS7M5wzHxFtL0pyKpi+MB6aDRBmYp51v9vD0L8Det/wQMX3GXsssUYMXo2MRwlyT60SXrAYL9cXRbNJbCocejldzHQRImsneWpgE7jn1IsToNdRJOPSholAG0dJ4QOGJ/xWxG5uwtFKn/XyoMKoz+04gPwKPI/k0UbBThr3SQQHRjJLuITQd6ZIP+DdOu1SMBFCHp+bdOB0rOogyiwvdpSzQKNdrIMc+zE3A920YG8rlQ2hT5nul7B4Qy9klUgxNHAwLtabH5UKYk="
    - secure: "BD0xHh11v334HC6B1bdOdFMSZsV89E9++gdC8Uvt45GCnHsnX96sLrgOwBHZxx3Cre7VF62hJbw/NeWkhf8W4UHAfOvzhXFTp52bENMh0GE8JfTnnuUMHg6GB2s19LLqPYFTSGPXFhMpMOPDJhGHdaIHkycoFyuNHXt7XBqKatGhHIWbjtVLRm7GX5PjFpbMD3ySvHwhya6H7wBfs3kTpqWH1bpqSmiQyRja6nIxNeAfv4dxp9g59mDjDDD2fNzG7Dzd99yJB9BY3Nmqdd8SJS6ak3O9J6pFSSw1nkfZLwEy1704FoloKDrCQ+2lv9+UHWtsAr06QYfDNU/P6HIc2fg66iG8KrsM5N7NnPPqdEWHm1ijWDbnbalq3LDbaldDoLT6ugviEHpVi1INZJ0xDXjz3WKx+JmE/fZfBP2U1aZCkaO9givdloszqFbaNXG0S+M4YFrMI8l1MZQ5puNBYipBwyM7dJUxGU1hPYlGaxf6gVSLC4Bquk5UoUsmM/eV7dGIZ01hsMuLXL5uDY8uahv0+zajNMhyCZS+07kirmmKHCcm9UefBsYe0aAzF05lo/AyMCtjF6N87CaH4KXFYnBfIQ2bpAXHFfb7OTcwDXoH1gGGUhWWBt3N7UPPBfSNNuciSSPZVOtMLl7g8XhINzqgFKO9KCWgN7U7iJqZ1lE="
    - secure: "16GZa4JbGfgmfIRWGX0fnYF3V3MJM6eY7SxcOBhXJNk7RiHoKXDQ7YB9MyOL7qja02I2tenII8bkQL/DkQboFp+b33FGGvwoPWIm4sYdhA6fbqt3bt5Vm/n3zibWymc6xJBAygN7vqGfpCPGR3wpsx8udafqHYLGF1P2P3nSUQ1fgU4kLbgYJtaEX0fRXIKfmRM038dnVt+1tdJIDVoiLZwbynEDyNcRt+pjdpNhYHcDWFq0ivlv1np7u7AdD6PP6hbvj6quAo9P2B2k5kBKr3fXYBRy2jQkDavDXauYa4Mhz8upmdmhyN3GYzDvv/N3yZjbaf0kxxc7aH/58n3iGsSTLaZ9cvkgjoTp8Rr8t1umvN1jiatjlQJ4RTqGdAazXsK0yHZspXdHaxLi76JGh1bTIONrbCsXQpFrY+rUQYFbZaDH7eF26Ulp6tiM6MhpUpAhFFeBeYUWy2qI1rscy7JMM/MfnfeURVxxfIa1U2caS6DLiuikgl1o4Z4ZyN3rA2mUb+Gs35w92DLnweqPAFC6UXKZQRnGdE3mdpwa8+YRFlK2wGrN1tbZRhLbzuW6mkeOhmud/v8b5W/0GE/XhnUB8zabNGXfKKd8BKFN4xcnEFVcbtzoR8tHXH6i9nNO3I0M3T0iiHJpU483+UBsr+MlVYJOa2/X/pe2MWbYO30="
