sudo: required
language: go
go:
- 1.10.x
git:
  depth: 1
services:
- docker
notifications:
  email:
    on_success: never
    on_failure: always
install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint
- dep ensure
script:
- make lint vet test
before_deploy:
- docker build --build-arg "VERSION=${TRAVIS_COMMIT:0:6}" -t "nrocco/bookmarks:${TRAVIS_COMMIT:0:6}" .
deploy:
  provider: script
  script:
  - 'echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin'
  - 'docker image tag nrocco/bookmarks:${TRAVIS_COMMIT:0:6} nrocco/bookmarks:latest'
  - 'docker image push nrocco/bookmarks:${TRAVIS_COMMIT:0:6}'
  - 'docker image push nrocco/bookmarks:latest'
  - 'wget -O /dev/null --header="Token: ${DEPLOY_TOKEN}" "https://webhooks.casadirocco.nl/hooks/deploy?service=bookmarks&tag=${TRAVIS_COMMIT:0:6}"'
  on:
    branch: master
