---
version: "3.7"
services:
  frontend:
    build:
      context: ./
      target: npmbase
    command: ["sh", "-c", "test -f node_modules/.bin/vue-cli-service || npm install; npm run serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web:/app/"
      - "node_modules:/app/node_modules"
  backend:
    build:
      context: ./
      target: gobase
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - "./:/src"
      - "go_modules:/go"
      - "bookmarks_state:/var/lib/bookmarks"
volumes:
  node_modules:
  go_modules:
  bookmarks_state:
