---
version: "3.7"
services:
  frontend:
    build:
      context: ./
      target: npmbuilder
    command: ["npm", "run", "serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web/public:/app/public"
      - "./web/src:/app/src"
      - "./web/package.json:/app/package.json"
      - "./web/package-lock.json:/app/package-lock.json"
      - "./web/vue.config.js:/app/vue.config.js"
  backend:
    build:
      context: ./
      target: gobuilder
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - "./:/src"
      - "/var/lib/bookmarks"
